#! /usr/bin/env bash

gcc *.c -o my_grep
./working_tests/run1.sh
./working_tests/run2.sh
./working_tests/run3.sh
./working_tests/run4.sh
./working_tests/run5.sh
./working_tests/run6.sh
./working_tests/run7.sh
./working_tests/run8.sh
./working_tests/run9.sh
./working_tests/run10.sh
./working_tests/run11.sh
./working_tests/run12.sh
./working_tests/run13.sh
./working_tests/run14.sh
./working_tests/run15.sh
./working_tests/run16.sh
./working_tests/run17.sh
./working_tests/run18.sh
./working_tests/run19.sh
~nimrodav/grep_tests/run1.sh
~nimrodav/grep_tests/run2.sh
~nimrodav/grep_tests/run3.sh
~nimrodav/grep_tests/run4.sh
~nimrodav/grep_tests/run5.sh
~nimrodav/grep_tests/run6.sh
~nimrodav/grep_tests/run7.sh
~nimrodav/grep_tests/run8.sh
~nimrodav/grep_tests/run9.sh
~nimrodav/grep_tests/run10.sh
~nimrodav/grep_tests/run11.sh
~nimrodav/grep_tests/run12.sh
~nimrodav/grep_tests/run13.sh
~nimrodav/grep_tests/run14.sh
~nimrodav/grep_tests/run15.sh
~nimrodav/grep_tests/run16.sh
~nimrodav/grep_tests/run17.sh
